name = "Example"
uuid = "7876af07-990d-54b4-ab0e-23690620f79a"
authors = ["Tanmay <tanmaykm@gmail.com>"]
version = "0.0.1"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
GitHub = "bc5e4493-9b4d-5f90-b8aa-2b2bcaad7a26"

[compat]
GitHub = "3.1.0, ^4.1.0"
julia = "1.0"
